export const CHANGE_CURRENT_INGREDIENT = "CHANGE_CURRENT_INGREDIENT";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CHANGE_INGREDIENT_POSITION = "CHANGE_INGREDIENT_POSITION";




